from server.models import IncidentDefinition


INCIDENT_TYPES: tuple[IncidentDefinition, ...] = (
    IncidentDefinition(
        id="INC001",
        name="API Timeout Cascade",
        severity="P2",
        difficulty="Easy",
        symptoms=[
            "Public API latency sustained above 5000ms for 11 minutes",
            "CPU saturation reached 95% on api-gateway pods",
            "HTTP 5xx error rate climbed to 50 requests per second",
        ],
        system_context={
            "service": "api-gateway",
            "language": "Python/FastAPI",
            "infra": "Kubernetes on EKS",
            "dependencies": ["auth-svc", "orders-api", "redis-sessions", "stripe-api"],
        },
        root_cause="Runaway retry storm on downstream auth calls exhausted worker threads and drove API timeouts",
        fix="Drain hot pods, cap downstream retries, and scale the gateway deployment while the auth timeout patch rolls out",
    ),
    IncidentDefinition(
        id="INC002",
        name="Database Connection Pool Exhaustion",
        severity="P1",
        difficulty="Easy",
        symptoms=[
            "Database pool usage locked at 500 of 500 connections",
            "P95 query latency exceeded 10 seconds for checkout writes",
            "Active query count held above 200 while request queues grew",
        ],
        system_context={
            "service": "checkout-svc",
            "language": "Python/FastAPI",
            "infra": "Kubernetes on EKS",
            "dependencies": ["postgres-orders", "redis-cart", "inventory-svc"],
        },
        root_cause="Leaked SQLAlchemy sessions after a checkout retry patch exhausted the primary Postgres pool",
        fix="Recycle checkout pods, terminate orphaned sessions, and roll back the retry patch until connection cleanup is fixed",
    ),
    IncidentDefinition(
        id="INC003",
        name="Deploy Regression / 5xx Spike",
        severity="P1",
        difficulty="Easy",
        symptoms=[
            "5xx error rate jumped from 0.2% to 18% after catalog query optimization deploy",
            "API latency p95 elevated from 145ms to 3.2 seconds",
            "Throughput fell from 1200 req/s to 890 req/s",
            "panic: runtime error or nil pointer dereference after deployment",
            "SIGSEGV fatal error following version rollout",
            "goroutine panic immediately after deploy or version change",
            "panic: slice bounds out of range after goroutine deployment on EKS",
            "Go runtime error: invalid memory address or nil pointer dereference",
            "fatal error: all goroutines are asleep - deadlock detected after deploy",
        ],
        system_context={
            "service": "api-service",
            "language": "Python/FastAPI",
            "infra": "Kubernetes on EKS",
            "dependencies": ["catalog-db", "cache-layer", "analytics-router"],
        },
        root_cause="A null-pointer regression in the catalog query filter optimization crashed the search endpoint",
        fix="Roll back the api-service deployment and redeploy once the null-check hotfix passes staging validation",
    ),
    IncidentDefinition(
        id="INC004",
        name="Cache Cardinality Explosion",
        severity="P2",
        difficulty="Medium",
        symptoms=[
            "Redis cache size expanded to 50GB in under 15 minutes",
            "Key cardinality crossed 100 million after the latest deploy",
            "Eviction rate sustained above 1000 keys per second",
            "Redis memory exhausted approaching OOM kill threshold on cache cluster",
            "Metrics label cardinality explosion causing unbounded time series growth",
            "Eviction rate spiked after new label dimensions added to metrics pipeline",
            "Memory limit reached due to high cardinality label or dimension expansion",
            "Unique time series count grew from thousands to millions after deploy",
            "Cache hit rate dropped and memory usage at 95% of allocated limit",
        ],
        system_context={
            "service": "catalog-api",
            "language": "Node.js",
            "infra": "GCP Cloud Run",
            "dependencies": ["redis-cache", "postgres-catalog", "pricing-svc"],
        },
        root_cause="A malformed cache key template embedded request UUIDs and caused unbounded key growth",
        fix="Roll back the cache key template, flush only the poisoned namespace, and reapply bounded TTLs for catalog fragments",
    ),
    IncidentDefinition(
        id="INC005",
        name="Queue Backlog Surge",
        severity="P1",
        difficulty="Medium",
        symptoms=[
            "Queue lag crossed 50000 messages and kept growing",
            "Consumer throughput flattened at 100 messages per second",
            "Partition depth increased continuously after the latest rollout",
            "Kafka consumer lag building up across topic partitions",
            "Consumer group processing at reduced msg/sec throughput",
            "Broker rebalancing or consumer group issues detected",
            "Offset lag or partition assignment problems",
            "Consumer lag offset delta: +50000 messages per minute on Kubernetes EKS cluster",
            "Kafka topic lag accumulation after consumer deployment on EKS",
            "Message queue backlog surge on Kubernetes cluster after rollout",
        ],
        system_context={
            "service": "billing-consumer",
            "language": "Go",
            "infra": "Kubernetes on GKE",
            "dependencies": ["kafka-cluster", "postgres-billing", "ledger-writer"],
        },
        root_cause="A rollout disabled consumer group rebalancing and left half the partitions unassigned",
        fix="Roll back the consumer deployment, trigger a rebalance, and temporarily scale workers until backlog returns to baseline",
    ),
    IncidentDefinition(
        id="INC006",
        name="Expired TLS Certificate On API Gateway",
        severity="P0",
        difficulty="Hard",
        symptoms=[
            "All external API calls fail TLS handshake",
            "Synthetic checks report certificate expired",
            "Internal services remain healthy behind the gateway",
        ],
        system_context={
            "service": "edge-gateway",
            "language": "Nginx",
            "infra": "AWS ALB + EC2",
            "dependencies": ["acm-cert", "public-dns"],
        },
        root_cause="Certificate rotation automation failed silently before renewal",
        fix="Attach the renewed certificate and restore the rotation alerting path",
    ),
    IncidentDefinition(
        id="INC007",
        name="Auth Dependency Slowdown",
        severity="P1",
        difficulty="Medium",
        symptoms=[
            "Auth token validation latency climbed above 1800ms",
            "Authenticated API requests timed out behind auth-svc",
            "Token cache hit rate collapsed during the slowdown window",
        ],
        system_context={
            "service": "auth-svc",
            "language": "Python/FastAPI",
            "infra": "Kubernetes on EKS",
            "dependencies": ["identity-provider", "token-cache", "api-gateway", "checkout-api"],
        },
        root_cause="Stricter certificate validation overhead in auth-svc amplified a downstream identity-provider slowdown and exhausted token validation capacity",
        fix="Reset the auth circuit breaker, restore token cache effectiveness, and roll back the enhanced validation path only if throughput does not recover",
    ),
    IncidentDefinition(
        id="INC008",
        name="Primary Region Message Queue Outage",
        severity="P0",
        difficulty="Nightmare",
        symptoms=[
            "Primary queue endpoint is unreachable from all app tiers",
            "Failover queue remains idle despite outage",
            "Order processing halts across two critical workflows",
        ],
        system_context={
            "service": "messaging-backbone",
            "language": "Platform",
            "infra": "Multi-region AWS",
            "dependencies": ["sqs-primary", "sqs-secondary", "route53-health-checks"],
        },
        root_cause="Regional failover automation did not switch producers to the standby queue",
        fix="Promote the standby queue endpoint and replay queued messages after traffic recovers",
    ),
    IncidentDefinition(
        id="INC009",
        name="CDN / Cache Invalidation Failure",
        severity="P2",
        difficulty="Medium",
        symptoms=[
            "CDN cache not propagating after content updates",
            "Stale responses returned from edge nodes despite purge requests",
            "Cache purge API returning 200 but content unchanged",
            "Geographic inconsistency in responses",
            "CloudFront or Fastly cache not invalidating correctly",
            "Edge nodes serving old cached content after deployment",
            "Cache invalidation API returned 200 but stale content served",
            "Cache-control headers present but edge nodes still returning stale",
            "TTL or cache purge configuration issue affecting CDN propagation",
        ],
        system_context={
            "service": "cdn-edge",
            "language": "Platform",
            "infra": "Fastly/CloudFront",
            "dependencies": ["fastly-api", "cloudfront", "origin-servers"],
        },
        root_cause="Cache invalidation request not propagating to all edge nodes or purge API misconfiguration",
        fix="Force purge all edge caches, verify propagation across regions, check CDN API configuration and TTL settings",
    ),
    IncidentDefinition(
        id="INC010",
        name="ML Model Degradation",
        severity="P2",
        difficulty="Medium",
        symptoms=[
            "Model returning generic or fallback responses to valid requests",
            "Cache hit rate dropping while latency remains normal",
            "Model version change correlating with output quality regression",
            "Feature store health showing data drift or pipeline failures",
            "Model precision or accuracy dropped significantly",
            "Model version change since incident started",
            "Training data drift or feature pipeline degradation detected",
            "Inference results showing low quality or generic predictions",
        ],
        system_context={
            "service": "ml-inference",
            "language": "Python/TensorFlow",
            "infra": "Kubernetes on EKS",
            "dependencies": ["feature-store", "model-registry", "inference-engine"],
        },
        root_cause="Model serving degraded outputs due to version regression, feature pipeline failure, or training data drift",
        fix="Roll back model version, verify feature pipeline health, check for training data drift, validate inference engine configuration",
    ),
    IncidentDefinition(
        id="INC011",
        name="Geographic / Routing Failure",
        severity="P2",
        difficulty="Medium",
        symptoms=[
            "Error rate varies significantly by user geography or region",
            "Subset of users in specific countries or regions affected",
            "Affects specific IP ranges or ISP routes",
            "Load balancer misconfiguration or DNS propagation issues",
            "BGP routing change affecting regional connectivity",
            "Route53 health checks failing for specific regions",
            "Regional availability or geographic isolation detected",
            "Specific region down APAC EU US affecting users",
            "DNS routing or edge node geographic mismatch",
        ],
        system_context={
            "service": "global-routing",
            "language": "Platform",
            "infra": "Multi-region AWS/GCP",
            "dependencies": ["route53", "load-balancer", "anycast-dns"],
        },
        root_cause="Regional routing misconfiguration, load balancer failover issue, or DNS propagation delay affecting specific geographies",
        fix="Check regional load balancer configuration, verify DNS propagation across geographies, test from multiple regions, adjust routing policies",
    ),
)


def load_incident_types() -> list[IncidentDefinition]:
    return list(INCIDENT_TYPES)
