from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class SystemContext(BaseModel):
    service: str
    language: str
    infra: str
    dependencies: list[str] = Field(default_factory=list)


class IncidentDefinition(BaseModel):
    id: str
    name: str
    severity: str
    difficulty: str
    symptoms: list[str]
    system_context: SystemContext
    root_cause: str
    fix: str


class AgentStubInfo(BaseModel):
    name: str
    implemented: bool = False


class IncidentRecord(BaseModel):
    nexus_incident_id: str
    external_id: str
    title: str
    severity: Literal["P1", "P2", "P3"]
    status: Literal["investigating", "resolved", "blocked_by_guardian"]
    source: Literal["datadog", "prometheus"] | None = None
    service: str = ""


class NormalizedAlertEnvelope(BaseModel):
    source: Literal["datadog", "prometheus"]
    external_id: str
    title: str
    severity: Literal["P1", "P2", "P3"]
    service: str
    detected_at: str
    observed_values: dict[str, object] = Field(default_factory=dict)


class IncidentLifecycleResponse(BaseModel):
    nexus_incident_id: str
    external_id: str
    title: str
    severity: Literal["P1", "P2", "P3"]
    status: Literal["investigating", "resolved", "blocked_by_guardian"]
    source: Literal["datadog", "prometheus"] | None = None
    recent_deployments: list[dict[str, object]] = Field(default_factory=list)


class SentinelClassification(BaseModel):
    """Structured output returned by the SENTINEL classifier."""

    incident_id: str
    incident_name: str
    severity: Literal["P1", "P2", "P3"]
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str


class PrismDiagnosis(BaseModel):
    """Structured output returned by the PRISM diagnosis step."""

    incident_id: str
    root_cause: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence: list[str] = Field(default_factory=list)
    queried_sources: list[str] = Field(default_factory=list)
    reasoning: str


class HistoricalRunbook(BaseModel):
    incident_id: str
    root_cause: str
    runbook_summary: str
    success_rate: float = Field(ge=0.0, le=1.0)
    similarity_score: float = Field(ge=0.0, le=1.0)


class RunbookScript(BaseModel):
    """Executable script generated by FORGE."""

    language: Literal["bash", "python", "kubectl"]
    code: str
    summary: str


class ForgeRunbookResult(BaseModel):
    """Structured output returned by FORGE runbook generation."""

    model_config = ConfigDict(protected_namespaces=())

    incident_id: str
    runbook: RunbookScript
    syntax_valid: bool
    model_name: str
    estimated_cost_usd: float = Field(ge=0.0)
    reasoning: str


class GuardianReviewResult(BaseModel):
    """Structured output returned by GUARDIAN safety review."""

    decision: Literal["approve", "reject", "request_modification"]
    safety_score: float = Field(ge=0.0, le=1.0)
    blocked_patterns: list[str] = Field(default_factory=list)
    reasoning: str


class SandboxValidationResult(BaseModel):
    syntax_valid: bool
    execution_allowed: bool
    issues: list[str] = Field(default_factory=list)


class IncidentContext(BaseModel):
    incident: IncidentDefinition
    incident_id: str
    raw_symptoms: list[str] = Field(default_factory=list)
    system_context: SystemContext
    signals: dict[str, list[str]] = Field(default_factory=dict)


class EpisodeReward(BaseModel):
    """Deterministic reward breakdown for a completed episode."""

    mttr: float = Field(ge=0.0, le=1.0)
    diagnosis: float = Field(ge=0.0, le=1.0)
    customer: float = Field(ge=0.0, le=1.0)
    coordination: float = Field(ge=0.0, le=1.0)
    oversight: float = Field(ge=0.0, le=1.0)
    severity_penalty: float = Field(ge=0.0, le=1.0)
    composite: float = Field(ge=0.0, le=1.0)


class Episode(BaseModel):
    """Synchronous Day 5 episode state used by the deterministic runner and grader."""

    incident: IncidentDefinition
    sentinel_output: SentinelClassification
    prism_output: PrismDiagnosis
    forge_output: ForgeRunbookResult
    guardian_output: GuardianReviewResult
    duration_minutes: float = Field(ge=0.0)
    verification_passed: bool
    executed: bool
    status: str
    communication_events: int = Field(ge=0)
    customer_impact_minutes: float = Field(ge=0.0)
    steps: list[str] = Field(default_factory=list)
    reward: EpisodeReward | None = None
